# Generated by Django 3.2.9 on 2022-07-27 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20220727_1741'),
        ('profiles', '0003_auto_20220726_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subdivision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.subdivision'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='position',
        ),
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.ManyToManyField(blank=True, null=True, to='organization.Position'),
        ),
    ]
