# Generated by Django 3.2.9 on 2022-07-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20220727_1741'),
        ('profiles', '0005_alter_profile_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.ManyToManyField(to='organization.Position'),
        ),
    ]
