# Generated by Django 3.2.9 on 2022-07-27 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20220727_1741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subdivision',
            options={'verbose_name': 'Подразделение', 'verbose_name_plural': 'Подразделения'},
        ),
    ]
